blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from rest_framework.documentation import include_docs_urls

schema_view = get_swagger_view(title='Blog')


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', schema_view),
    path('docs/', include_docs_urls(title='BlogAPI')),
    path('api/v1/accounts/', include(('accounts.urls',  'accounts'), namespace="accounts-api")),
    path('api/v1/forum/', include(('forum.urls', 'forum'), namespace='forum-api')),
    path('api/v1/chat/', include(('chat.urls', 'chat'), namespace='chat-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, re_path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('messages/', views.message_list, name='message-list'),

]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.message}'

    class Meta:
        ordering = ('timestamp',)

chat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .models import Message
from .serializers import MessageSerializer
from rest_framework.generics import ListCreateAPIView
from rest_framework.views import APIView
from django.http import Http404
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer
from django.contrib.auth.models import User
from rest_framework.response import Response
from django.http.response import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from rest_framework.parsers import JSONParser
from online_users.models import OnlineUserActivity
from datetime import timedelta

# Create your views here.


def index(request):
    if request.user.is_authenticated:
        return redirect('chat-api:chats')
    if not request.user.is_authenticated:
        return redirect('accounts-api:login')
    if request.method == 'GET':
        return render(request, 'index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chat-api:chats')


@csrf_protect
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=status.HTTP_201_CREATED)
        return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def chat_view(request):
    """Render the template with required context variables"""
    if not request.user.is_authenticated:
        return redirect('accounts-api:login')
    if request.method == "GET":
        user_activity_objects = OnlineUserActivity.get_user_activities(timedelta(minutes=60))
        active_users = (user for user in user_activity_objects)
        return render(request, 'chat.html',
                      {'users': User.objects.exclude(username=request.user.username),
                       'active_users': active_users})


def message_view(request, sender, receiver):
    """Render the template with required context variables"""
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'messages.html',
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})


class MessageList(ListCreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer


class MessageDetail(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, sender=None, receiver=None):
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    def post(self, request):
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=status.HTTP_201_CREATED)
        return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

chat/templates/chat.html
{% extends 'index.html' %}
{% block 'body' %}

<nav class="black lighten-3">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">Chat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="">{{ request.user.username }}</a></li>
          <li><a href="{% url 'accounts-api:logout' %}?next=/api/v1/accounts/login/"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% for active in active_users %}
                <a href="{% url 'chat-api:chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT300BAyRnpGukBNCNKaFN0QQW2Y7y5BaV3FmWCxlE8mTs1Hy5x&usqp=CAU" class="col s4">
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{ active.user }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block 'messages' %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}


                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>


<script>
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');

            })
            setInterval(() => {
                getUsers({{ request.user.id }}, doc => {
                    let list = ''
                    doc.map(userItem => {
                        list += userItem
                    })
                    $('#users').html(list)
                });
            }, 1000)
        })

</script>

{% endblock %}

chat/templates/messages.html
{% extends 'chat.html' %}
{% block hide %}{% endblock %}
{% block 'messages' %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

chat/templates/reg.html
{% extends 'index.html' %}
{% block 'body' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input name="username" id="id_username" type="text" class="validate invalid">
                <label for="id_username" data-error="Username already taken">Username</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="id_password" type="password">
                <label for="id_password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password2" id="id_password2" type="password">
                <label for="id_password2">Repeat Password</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button class="btn blue waves-effect waves-light pull-s12">Register</button>
            </div>
            </div>
        </div>
    </form>
    <script>
    //Script for validating user registration.
    $(function () {
        $('#register-form').on('submit', function (event) {
            event.preventDefault(); //Prevent the default behavior on submit.
            var username = $('#id_username').val();
            var password;
            if(username !== '') //Check if username in not blank
            {
                password = $('#id_password').val();
                if(password !== '' && password === $('#id_password2').val()) //Check if password is not blank and matches with the confirmation.
                {
                    register(username, password); //Calling register function, which we will define in 'chat.js'
                }
                else{
                    alert("The passwords doesn't match!");
                }
            }
            else
                alert("Please enter a valid username!");
        })
    })
    </script>
{% endblock %}
{% endblock %}